name: example
description: Open AI example app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  logging: ^1.1.0
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  unofficial_chat_gpt_open_api:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true