name: unofficial_open_api
description: Open AI package for Dart
version: 1.0.1
homepage: https://www.federicoviceconti.com
repository: https://github.com/federicoviceconti/unofficial_open_ai

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  chopper: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  chopper_generator: ^6.0.0

flutter: